api_platform:
  title: 'Koillection API'
  version: 1.5.13
  show_webby: false

  formats:
    jsonld: [ 'application/ld+json' ]
    json: [ 'application/json' ]
    html: [ 'text/html' ]
  docs_formats:
    jsonld: [ 'application/ld+json' ]
    json: [ 'application/json' ]
    jsonopenapi: [ 'application/vnd.openapi+json' ]
    html: [ 'text/html' ]

  defaults:
    cache_headers:
      vary: [ 'Content-Type', 'Authorization', 'Origin' ]
    extra_properties:
      standard_put: false
    normalization_context:
      skip_null_values: false
  use_symfony_listeners: true

