doctrine_migrations:
    migrations_paths:
        'App\Migrations\Mysql': '%kernel.project_dir%/migrations/Mysql'
        'App\Migrations\Postgresql': '%kernel.project_dir%/migrations/Postgresql'
    storage:
        table_storage:
            table_name: doctrine_migration_version
    check_database_platform: true