# Project language
language: php
php:
  - 7.4

# Allows use container-based infrastructure
sudo: false

# Start mysql service
services:
  - postgresql

# Cache composer packages so "composer install" is faster
cache:
  directories:
    - $HOME/.composer/cache/files

# Matrix to test in every php version
matrix:
  # Fast finish allows to set the build as "finished" even if the "allow_failures" matrix elements are not finished yet.
  fast_finish: true
  include:
    - php: 7.4

# Install composer dependencies,
# Create database, schema and fixtures
install:
  - echo "extension = apcu.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer self-update
  - touch .env.local
  - echo "APP_ENV=test" >> .env.local
  - echo "APP_DEBUG=0" >> .env.local
  - echo "APP_SECRET=WBp61O25u2ysihh4N4FEGwIOfOrfTU" >> .env.local
  - echo "DB_NAME=koillection" >> .env.local
  - echo "DB_HOST=127.0.0.1" >> .env.local
  - echo "DB_PORT=5432" >> .env.local
  - echo "DB_USER=postgres" >> .env.local
  - echo "DB_PASSWORD=" >> .env.local
  - echo "DB_VERSION=11" >> .env.local
  - SYMFONY_ENV=test composer install -o
  - psql -c 'create database koillection;' -U postgres
  - php bin/console doctrine:schema:create --env=test
  - php bin/console doctrine:fixtures:load --env=test --no-interaction

# Run script
script:
   - php bin/console cache:warmup --env=test
   - php -d memory_limit=512M ./bin/phpunit --stderr


# After a build, send email notification with the build results
notifications:
  email: koillection@gmail.com
