#This docker-compose file is provided for dev purposes
version: '3'

services:
    #FPM image
    koillection:
        image: docker.pkg.github.com/benjaminjonard/koillection/fpm:v1.1
        restart: always
        ports:
            - 80:80
        environment:
            - APP_ENV=dev
            - APP_DEBUG=1
            - DB_NAME=koillection
            - DB_HOST=postgres
            - DB_PORT=5432
            - DB_USER=root
            - DB_PASSWORD=m6iFpZTkR1U6klSvLtRF
            - DB_VERSION=10.4
            - PHP_TZ=Europe/Paris
        depends_on:
            - postgres
        volumes:
            #- ./docker/volumes/koillection/conf:/conf
            #- ./docker/volumes/koillection/uploads:/uploads
            - ./:/var/www/koillection
            - ./docker/volumes/php/php.ini:/usr/local/etc/php/php.ini

    postgres:
        container_name: postgres
        image: postgres:10-alpine
        environment:
            - POSTGRES_DB=koillection
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=m6iFpZTkR1U6klSvLtRF
        ports:
            - 5432:5432
        volumes:
            - "./docker/volumes/postgresql:/var/lib/postgresql/data"
