#This docker-compose file is provided for dev purposes
version: '3'

services:
    #FPM image
    koillection:
        container_name: koillection
        image: koillection/koillection:dev
        restart: always
        ports:
            - 80:80
        environment:
            - APP_ENV=dev
            - APP_DEBUG=1
            - DB_DRIVER=pdo_mysql
            - DB_NAME=koillection
            - DB_HOST=mysql
            - DB_PORT=3306
            - DB_USER=root
            - DB_PASSWORD=m6iFpZTkR1U6klSvLtRF
            - DB_VERSION=8
            - PHP_TZ=Europe/Paris
            - HTTPS_ENABLED=0
        depends_on:
            - mysql
            - postgresql
        volumes:
            - "./docker/volumes/koillection/public/uploads:/var/www/koillection/public/uploads"
            - ./:/var/www/koillection

    postgresql:
        container_name: postgresql
        image: postgres:14
        environment:
            - POSTGRES_DB=koillection
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=m6iFpZTkR1U6klSvLtRF
            - POSTGRES_HOST_AUTH_METHOD=trust
        ports:
            - 5432:5432
        volumes:
            - "./docker/volumes/postgresql:/var/lib/postgresql/data"

    mysql:
        container_name: mysql
        image: mysql:latest
        environment:
            - MYSQL_ROOT_PASSWORD=m6iFpZTkR1U6klSvLtRF
            - MYSQL_DATABASE=koillection

        ports:
            - 3306:3306
        volumes:
            - "./docker/volumes/mysql:/var/lib/mysql"

    pgadmin:
        image: dpage/pgadmin4
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: root
        ports:
            - "8080:80"
